import type { NextPage } from 'next'
import Head from 'next/head'
import s from '../styles/Home.module.scss'
import { Task } from '../components/Task'

const Home: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <p className={s.description}>
          Task app{' '}
        </p>
        <Task />
      </main>

    </div>
  )
}

export default Home
