import type { NextPage } from 'next'
import Head from 'next/head'
import s from '../styles/Home.module.scss'
import { Task } from '../components/Task'

const Home: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h1 className={s.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={s.description}>
          Get started by editing{' '}
          <code className={s.code}>pages/index.js</code>
        </p>
        <Task />
      </main>

    </div>
  )
}

export default Home
